[[LibPQ]]
arch = "aarch64"
git-tree-sha1 = "5d72e98eddac8090bb1a9cd0ee24bfcc892dec7c"
os = "macos"

    [[LibPQ.download]]
    sha256 = "130b2862768699f92a4b2396c5e75423c0f15e44d8f23715cc9ef47f1c03a495"
    url = "https://github.com/AHRIORG/LibPQ_jll.jl/releases/download/LibPQ-v18.1.0+1/LibPQ.v18.1.0.aarch64-apple-darwin20.tar.gz"
[[LibPQ]]
arch = "aarch64"
git-tree-sha1 = "ef8f926d6838b622966af81b8479dbfd1e0b02ae"
libc = "glibc"
os = "linux"

    [[LibPQ.download]]
    sha256 = "286351b4c66f14f497afbe463f2067640c351b7c2cdea79a3908153314dd5583"
    url = "https://github.com/AHRIORG/LibPQ_jll.jl/releases/download/LibPQ-v18.1.0+1/LibPQ.v18.1.0.aarch64-linux-gnu.tar.gz"
[[LibPQ]]
arch = "aarch64"
git-tree-sha1 = "d0199754398b88bcb69c0e0bf87becd3b4bce383"
libc = "musl"
os = "linux"

    [[LibPQ.download]]
    sha256 = "1852e0d3b6aaae64dc74515e8543b01229f29c3b56522fd1dd9d1193557489af"
    url = "https://github.com/AHRIORG/LibPQ_jll.jl/releases/download/LibPQ-v18.1.0+1/LibPQ.v18.1.0.aarch64-linux-musl.tar.gz"
[[LibPQ]]
arch = "x86_64"
git-tree-sha1 = "039d84801f2a70a79bd721f15feb00da8a10893d"
libc = "glibc"
os = "linux"

    [[LibPQ.download]]
    sha256 = "1fec27457959fcaf38868e62a78881448c41146d51c9c1968120746783da303f"
    url = "https://github.com/AHRIORG/LibPQ_jll.jl/releases/download/LibPQ-v18.1.0+1/LibPQ.v18.1.0.x86_64-linux-gnu.tar.gz"
[[LibPQ]]
arch = "x86_64"
git-tree-sha1 = "1328842f007a5d6dc7caef5c379b7d64ec7b7bf7"
libc = "musl"
os = "linux"

    [[LibPQ.download]]
    sha256 = "c89847e978b310c8908e6e78d75ea77e5be2c7d3ee7f9b92c9aba87eaf19d7e6"
    url = "https://github.com/AHRIORG/LibPQ_jll.jl/releases/download/LibPQ-v18.1.0+1/LibPQ.v18.1.0.x86_64-linux-musl.tar.gz"
[[LibPQ]]
arch = "x86_64"
git-tree-sha1 = "d190e681eb9f8d607560af94bb8ce7a7bdafbcb2"
os = "windows"

    [[LibPQ.download]]
    sha256 = "bdd37066166cda7614d2a6809a0373e1dcaab6a597251c93280249683deb0cfa"
    url = "https://github.com/AHRIORG/LibPQ_jll.jl/releases/download/LibPQ-v18.1.0+1/LibPQ.v18.1.0.x86_64-w64-mingw32.tar.gz"
